export enum Platform {
  Github = 'Github',
  FrontendMentor = 'FrontendMentor',
  Twitter = 'Twitter',
  LinkedIn = 'LinkedIn',
  Youtube = 'Youtube',
  Facebook = 'Facebook',
  Twitch = 'Twitch',
  DevTo = 'DevTo',
  CodeWars = 'CodeWars',
  FreeCodeCamp = 'FreeCodeCamp',
  GitLab = 'GitLab',
  HashNode = 'HashNode',
  StackOverflow = 'StackOverflow', 
  CodePen = 'CodePen',
}
